### ISSUE TITLE
.gitlab-ci.yml?

### ISSUE THREAD

**Issue by Alberto199810** [voila-dashboards/voici-demo#16]
I'd like to see the same deployment that happens on github (with the deploy.yml) also translated into a .gitlab-ci.yml, to apply the
same process also on GitLab and not only on GitHub. Is it in the roadmap? Does it already exist?

**Comment by jtpio** [comment]
Thanks @Alberto199810. 

The approach would be similar to the one documented in JupyterLite: https://jupyterlite.readthedocs.io/en/stable/howto/deployment/gitlab.html. Maybe there could be a link to that page in the Voici docs, or mention how to use the `voici` CLI directly in the Voici docs.

**Comment by Alberto199810** [comment]
Hey @jtpio, thanks for the answer. I'd like to ask you another question: is it possible to make (in some way) the build step free from "xeus-lite" package? Or is it compulsory to have it?
Thanks

**Comment by jtpio** [comment]
Are you referring to the xeus python kernel? In that case it's not mandatory indeed. You can use another kernel for code execution if you would like to. But for demo purposes it's included here in the demo repo so code can be executed.

**Comment by Alberto199810** [comment]
No, the fact is that when I launch “voici build —contents content” it automatically starts, as a first phase, downloading “xeus-lite” (https://github.com/jupyter-xeus/xeus-lite). Unfortunately, since I’m not working on public repositories, I’d need to skip the download of this package here, if not required. How can this be achieved?

**Comment by jtpio** [comment]
ok in that case you could use the Pyodide kernel instead by replacing:

https://github.com/voila-dashboards/voici-demo/blob/958cd36ed15a24188f4e9997f31c1de5701ccb2b/build-environment.yml#L7

With `jupyterlite-pyodide-kernel`. Both are Python kernels but they have some differences: https://jupyterlite.readthedocs.io/en/stable/howto/configure/kernels.html#choosing-a-kernel

**Comment by Alberto199810** [comment]
Hello @jtpio, it actually worked, so now I manage to deploy the whole solution. Problem of this approach is that now it seems to not install the packages I specify in environments.yml, since in the Jupyter Notebook in GL Pages throws an error due to missing package.
After looking at the build log, I see:
“””
ERROR: pip’s dependency resolver does not currently take into account that all the packages are installed. This behavior is the source of the following dependency conflics.
  Jupyterlite-pyodide-kernel 0.2.0 requires Jupiterlite-core<0.3.0,>=0.2.0, but you have Jupyterlite-core 0.1.3 which is incompatible
“””
Actually, firstly It installed jupyterlite-core 0.2.0 but then it uninstalled because voici requires 0.1.3.

Is there a way to fix this error? I’m using voici 0.4.6.
Hope you have a solution also for this!

**Comment by Alberto199810** [comment]
Ok I think I found the issue:
basically, this step is never happening -->
"""
Transaction
  Prefix: /tmp/xeus-python-kernel/envs/voici
  Updating specs:
   - python=3.10
   - xeus-lite
   - xeus-python=0.15.9
   - ipywidgets=8.0.6
   - jupyterlab_widgets=3.0.7
   - pandas[version='<2']
   - bqplot
   - plotly
   - ipywidgets   
""" 
if I use jupyterlite-pyodide-kernel. Any suggestions?

**Comment by martinRenou** [comment]
If you use `jupyterlite-pyodide-kernel`, you won't be able to pre-install packages from the `environment.yml` file. This feature is what `jupyterlite-xeus-python` provides.

It's unclear to me why `xeus-lite` is being downloaded from Github, are you using a dev install?

Isn't it trying to download it from https://beta.mamba.pm/get/emscripten-forge/emscripten-wasm32/xeus-lite-1.0.2-h5c9267c_1.tar.bz2 instead?

**Comment by Alberto199810** [comment]
Thank you Martin for the reply. Unfortunately, in my environment I can only use packages listed on pypi.org, and since package is not there it fails to load everything if I use xeus kernel. Is there a way to onboard the xeus-lite package there?

**Comment by martinRenou** [comment]
> Is there a way to onboard the xeus-lite package there?

It's very improbable that this will happen as it's not a Python package.

What could happen in a near-ish future though is that we could install packages at runtime with some kind of mamba-lite that is compiled into WASM and can install packages from the web-page, similar to what pip-lite does in `jupyterlite-pyodide-kernel`.
