### ISSUE TITLE
Drop the JupyterLite `--contents` CLI option?

### ISSUE THREAD

**Issue by jtpio** [voila-dashboards/voici-demo#19]
The build command now uses two ways for proving contents:

https://github.com/voila-dashboards/voici-demo/blob/0af62aeb70ecc31d7ba6a789ff11ecf82c1e162d/.github/workflows/deploy.yml#L31

From an outside perspective, it could confuse users who may not know what the differences between the two are.

Maybe we can simplify it with the following:

```yaml
 run: voici build --output-dir dist --XeusAddon.mounts content:/content 
```

**Comment by martinRenou** [comment]
Thank you for this suggestion. Indeed this may be confusing.

We could probably hide this complexity behind a Voici CLI option that dispatches the content to jupyterlite-core and jupyterlite-xeus.

I think this should be included in the PR that makes automatic use of the jupyterlite-xeus's mounts option to transparently ship content as part of the xeus kernel if it's installed.

**Comment by jtpio** [comment]
> We could probably hide this complexity behind a Voici CLI option that dispatches the content to jupyterlite-core and jupyterlite-xeus.

Not sure. Shouldn't Voici be kernel agnostic? 

The suggestion was mostly for this voici demo (and folks using it for the first time).

Also it may be interesting to use this `--XeusAddon.mounts` option in JupyterLite as well, which could make sense for `jupyterlite-sphinx` and Notebook 7 too.

Ideally there shoudn't be too many differences between JupyterLite and Voici (and contents in JupyterLite be fixed so it's less flaky) to keep the behavior consistent.

**Comment by martinRenou** [comment]
This is now fixed with latest jupyterlite-xeus!
