### ISSUE TITLE
Kernel Missing

### ISSUE THREAD

**Issue by Alberto199810** [voila-dashboards/voici-demo#23]
Hello guys, I'm working on GitLab, and I'm using your library to deploy the Jupyter Notebook on GL Pages. The Pipeline end in success, and everything seems fine, apart from the fact that when I try to launch the page, it is stuck at the "Running" phase.

It seemed to me that the Kernel was not starting, and indeed in the deploy pipeline I've found this row:
"""
{...}/python3.10/site-packages/jupyterlite_xeus/add_on.py: UserWarning: kernel binaries not found for xpython-raw
"""

And then again same thing:

"""
{...}/python3.10/site-packages/jupyterlite_xeus/add_on.py: UserWarning: kernel binaries not found for xpython
"""

So, my feeling is that apparently it is not recognizing the kernel. Any idea in how to solve this?

**Comment by martinRenou** [comment]
Thank you for opening an issue, I will transfer this into https://github.com/jupyterlite/xeus, let's continue the discussion there.

**Comment by martinRenou** [comment]
See https://github.com/jupyterlite/xeus/issues/61
